CREATE TABLE `venues` (
  `venue_id` int NOT NULL PRIMARY KEY,
  `name` varchar(100) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `status` varchar(10) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL
);


INSERT INTO `venues` VALUES ("30","Robert F. Kennedy Memorial Stadium","Washington, District of Columbia","active","1961-10-01","NULL");
INSERT INTO `venues` VALUES ("33","Giants Stadium","East Rutherford, New Jersey","demolished","1976-10-10","2010-01-03");
INSERT INTO `venues` VALUES ("44","Estadio Jornalista Mário Filho (Maracanã)","Rio de Janeiro, Rio de Janeiro","active","1950-06-16","NULL");
INSERT INTO `venues` VALUES ("53","Estádio Adelmar da Costa Carvalho","Recife, Pernambuco","active","1937-07-04","NULL");
INSERT INTO `venues` VALUES ("56","Estádio Municipal Paulo Machado de Carvalho","São Paulo, São Paulo","active","1940-04-27","NULL");
INSERT INTO `venues` VALUES ("58","Estádio Durival de Brito e Silva","Curitiba, Paraná","active","1947-01-23","NULL");
INSERT INTO `venues` VALUES ("84","Goodison Park","Liverpool","active","1892-08-24","NULL");
INSERT INTO `venues` VALUES ("86","Villa Park","Birmingham","active","1897-04-17","NULL");
INSERT INTO `venues` VALUES ("114","Stade de Gerland","Lyon","active","1926-05-01","NULL");
INSERT INTO `venues` VALUES ("115","Stade Jacques Chaban-Delmas","Bordeaux","active","1938-06-12","NULL");
INSERT INTO `venues` VALUES ("122","Stade Vélodrome","Marseille","active","1937-06-13","NULL");
INSERT INTO `venues` VALUES ("125","Parc des Princes","Paris","active","1897-07-18","NULL");
INSERT INTO `venues` VALUES ("126","Stade Geoffroy-Guichard","Saint-Ètienne","active","1931-09-13","NULL");
INSERT INTO `venues` VALUES ("127","Stade de la Meinau","Strasbourg","active","1906-01-01","NULL");
INSERT INTO `venues` VALUES ("129","Stade Bollaert-Delelis","Lens","active","1933-06-18","NULL");
INSERT INTO `venues` VALUES ("130","Stadium Municipal","Toulouse","active","1937-01-01","NULL");
INSERT INTO `venues` VALUES ("182","Commerzbank-Arena","Frankfurt am Main","active","1925-05-21","NULL");
INSERT INTO `venues` VALUES ("183","HDI-Arena","Hannover","active","1954-09-26","NULL");
INSERT INTO `venues` VALUES ("184","Mercedes-Benz-Arena","Stuttgart","active","1933-07-23","NULL");
INSERT INTO `venues` VALUES ("185","Olympiastadion Berlin","Berlin","active","1936-08-01","NULL");
INSERT INTO `venues` VALUES ("186","Signal-Iduna-Park","Dortmund","active","1974-04-02","NULL");
INSERT INTO `venues` VALUES ("192","Stadio Giuseppe Meazza","Milano","active","1926-09-19","NULL");
INSERT INTO `venues` VALUES ("193","Stadio Olimpico di Torino","Torino","active","1933-05-14","NULL");
INSERT INTO `venues` VALUES ("194","Stadio Artemio Franchi","Firenze","active","1931-09-13","NULL");
INSERT INTO `venues` VALUES ("195","Stadio Communale Friuli","Udine","active","1976-09-26","NULL");
INSERT INTO `venues` VALUES ("196","Stadio Comunale Luigi Ferraris","Genova","active","1911-01-22","NULL");
INSERT INTO `venues` VALUES ("198","Stadio Renzo Barbera","Palermo","active","1932-01-24","NULL");
INSERT INTO `venues` VALUES ("199","Stadio San Paolo","Napoli","active","1959-09-06","NULL");
INSERT INTO `venues` VALUES ("201","Stadio Olimpico","Roma","active","1932-01-01","NULL");
INSERT INTO `venues` VALUES ("207","Stadio Sant'Elia","Cagliari","active","1970-09-12","NULL");
INSERT INTO `venues` VALUES ("240","Estadio Nemesio Díez","Toluca de Lerdo","active","1954-08-18","NULL");
INSERT INTO `venues` VALUES ("244","Estadio Azteca","Coyoacán, Ciudad de México (D.F.)","active","1966-05-29","NULL");
INSERT INTO `venues` VALUES ("246","Estadio Olímpico de Universitario","Coyoacán, Ciudad de México (D.F.)","active","1952-11-20","NULL");
INSERT INTO `venues` VALUES ("252","Estadio Cuauhtémoc","Puebla","active","1968-10-08","NULL");
INSERT INTO `venues` VALUES ("253","Estadio Tres de Marzo","Zapopan, Guadalajara","active","1971-01-01","NULL");
INSERT INTO `venues` VALUES ("254","Estadio Universitario de Nuevo León","San Nicolás de los Garza","active","1967-05-30","NULL");
INSERT INTO `venues` VALUES ("255","Estadio Tecnológico","Monterrey","active","1950-07-17","NULL");
INSERT INTO `venues` VALUES ("257","Estadio Jalisco","Guadalajara","active","1960-01-31","NULL");
INSERT INTO `venues` VALUES ("337","Nya Ullevi","Göteborg","active","1958-05-29","NULL");
INSERT INTO `venues` VALUES ("338","Örjans Vall","Halmstad","active","1922-07-30","NULL");
INSERT INTO `venues` VALUES ("339","Olympia","Helsingborg","active","1898-07-31","NULL");
INSERT INTO `venues` VALUES ("343","Behrn Arena","Örebro","active","1923-08-26","NULL");
INSERT INTO `venues` VALUES ("345","Norrköpings Idrottspark (Nya Parken)","Norrköping","active","1903-01-01","NULL");
INSERT INTO `venues` VALUES ("346","Råsundastadion","Solna","demolished","1937-04-18","2012-11-22");
INSERT INTO `venues` VALUES ("364","Estadio Santiago Bernabéu","Madrid","active","1947-12-14","NULL");
INSERT INTO `venues` VALUES ("365","Camp Nou","Barcelona","active","1957-09-24","NULL");
INSERT INTO `venues` VALUES ("366","Estadio Vicente Calderón","Madrid","active","1966-10-02","NULL");
INSERT INTO `venues` VALUES ("370","Estadio de Mestalla","Valencia","active","1923-05-20","NULL");
INSERT INTO `venues` VALUES ("372","Estadio Ramón Sánchez Pizjuán","Sevilla","active","1958-09-07","NULL");
INSERT INTO `venues` VALUES ("373","Estadio de la Romareda","Zaragoza","active","1957-09-08","NULL");
INSERT INTO `venues` VALUES ("380","Estadio San Mamés","Bilbao","demolished","1913-08-21","2013-06-09");
INSERT INTO `venues` VALUES ("384","Estadio Municipal José Zorrilla","Valladolid","active","1982-02-20","NULL");
INSERT INTO `venues` VALUES ("386","Estadio Municipal de Riazor","A Coruña (La Coruña)","active","1944-10-28","NULL");
INSERT INTO `venues` VALUES ("430","Old Trafford","Manchester","active","1910-02-19","NULL");
INSERT INTO `venues` VALUES ("434","Estadio La Rosaleda","Málaga","active","1941-04-13","NULL");
INSERT INTO `venues` VALUES ("435","Estadio Municipal El Molinón","Gijón","active","1908-05-20","NULL");
INSERT INTO `venues` VALUES ("443","Stadio Marc'Antonio Bentegodi","Verona","active","1963-12-15","NULL");
INSERT INTO `venues` VALUES ("444","Stadio Renato Dall'Ara","Bologna","active","1927-05-29","NULL");
INSERT INTO `venues` VALUES ("446","Stade de la Beaujoire - Louis Fonteneau","Nantes","active","1984-05-08","NULL");
INSERT INTO `venues` VALUES ("462","Hillsborough Stadium","Sheffield","active","1899-09-02","NULL");
INSERT INTO `venues` VALUES ("590","Soldier Field","Chicago, Illinois","active","1924-10-09","NULL");
INSERT INTO `venues` VALUES ("595","Rose Bowl","Pasadena, California","active","1922-10-08","NULL");
INSERT INTO `venues` VALUES ("711","Cotton Bowl","Dallas, Texas","active","1930-10-01","NULL");
INSERT INTO `venues` VALUES ("823","Estadio La Corregidora","Santiago de Querétaro","active","1985-02-05","NULL");
INSERT INTO `venues` VALUES ("938","Stade Olympique de la Pontaise","Lausanne","active","NULL","NULL");
INSERT INTO `venues` VALUES ("946","Stadio di Cornaredo","Lugano","active","1951-01-01","NULL");
INSERT INTO `venues` VALUES ("976","Estadio José Amalfitani","Capital Federal, Ciudad de Buenos Aires","active","1943-04-11","NULL");
INSERT INTO `venues` VALUES ("979","Estadio Malvinas Argentinas","Mendoza, Provincia de Mendoza","active","1978-05-14","NULL");
INSERT INTO `venues` VALUES ("988","Estadio Dr. Lisandro de la Torre","Rosario, Provincia de Santa Fe","active","1929-10-27","NULL");
INSERT INTO `venues` VALUES ("989","Estadio Monumental Antonio Vespucio Liberti","Capital Federal, Ciudad de Buenos Aires","active","1938-05-25","NULL");
INSERT INTO `venues` VALUES ("998","Estadio José María Minella","Mar del Plata, Provincia de Buenos Aires","active","1978-05-21","NULL");
INSERT INTO `venues` VALUES ("1006","Estadio Mario Alberto Kempes","Ciudad de Córdoba, Provincia de Córdoba","active","1978-05-16","NULL");
INSERT INTO `venues` VALUES ("1156","Estadio Sergio León Chávez","Irapuato","active","NULL","NULL");
INSERT INTO `venues` VALUES ("1158","Estadio León (Nou Camp)","León de los Aldamas","active","NULL","NULL");
INSERT INTO `venues` VALUES ("1161","Estadio Universidad Tecnológica de Nezahualcóyotl","Ciudad Nezahualcóyotl","active","NULL","NULL");
INSERT INTO `venues` VALUES ("1220","Stade de la Mosson","Montpellier","active","NULL","NULL");
INSERT INTO `venues` VALUES ("1672","Stadio Comunale San Nicola","Bari","active","NULL","NULL");
INSERT INTO `venues` VALUES ("1724","Estadio Centenario","Montevideo","active","1930-07-18","NULL");
INSERT INTO `venues` VALUES ("1725","Estadio Gran Parque Central","Montevideo","active","NULL","NULL");
INSERT INTO `venues` VALUES ("1855","Estadio de Balaídos","Vigo","active","1928-12-30","NULL");
INSERT INTO `venues` VALUES ("1857","Estadio Manuel Martínez Valero","Elche","active","1976-09-08","NULL");
INSERT INTO `venues` VALUES ("1866","Estadio José Rico Pérez","Alicante","active","1974-08-03","NULL");
INSERT INTO `venues` VALUES ("1871","Estadio Benito Villamarín","Sevilla","active","1929-03-17","NULL");
INSERT INTO `venues` VALUES ("2377","Stade Olympique Yves-du-Manoir","Colombes","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2378","Stade Charles Argentin","Le Havre","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2578","Estadio Pocitos","Montevideo","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2579","Stadio Giorgio Ascarelli","Napoli","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2580","Stadio del Partito Nazionale Fascista","Roma","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2581","Stadio Giuseppe Grezar","Trieste","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2582","Stade du Fort Carré","Antibes","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2583","Stade Henri-Jooris","Lambersart","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2584","Stade Auguste Delaune (old)","Reims","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2585","Estádio Raimundo Sampaio (old)","Belo Horizonte, Minas Gerais","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2586","Estádio Ildo Meneghetti","Porto Alegre, Rio Grande do Sul","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2587","St. Jakob-Park (old)","Basel","demolished","1954-04-21","1998-12-12");
INSERT INTO `venues` VALUES ("2588","Wankdorfstadion","Bern","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2589","Stade des Charmilles","Genève","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2590","Hardturm-Stadion","Zürich","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2591","Malmö Stadion","Malmö","active","1958-05-28","NULL");
INSERT INTO `venues` VALUES ("2592","Tunavallen","Eskilstuna","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2593","Jernvallen","Sandviken","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2594","Ryavallen","Borås","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2595","Rimnersvallen","Uddevalla","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2596","Arosvallen","Västerås","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2597","Estadio Carlos Dittborn","Arica","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2598","Estadio El Teniente","Rancagua","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2599","Estadio Nacional Julio Martínez Prádanos","Santiago de Chile","active","1938-12-03","NULL");
INSERT INTO `venues` VALUES ("2600","Estadio Sausalito","Viña del Mar","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2601","Wembley Stadium (old)","London","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2602","Roker Park","Sunderland","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2603","White City Stadium","London","demolished","1908-04-27","1985-01-01");
INSERT INTO `venues` VALUES ("2604","Ayresome Park","Middlesbrough, North Yorkshire","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2605","Olympiastadion München","München","active","1972-05-26","NULL");
INSERT INTO `venues` VALUES ("2733","Stade de France","Paris","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2734","Silverdome","Pontiac, Michigan","inactive","1975-08-23","NULL");
INSERT INTO `venues` VALUES ("2735","Stanford Stadium (old)","Stanford, California","demolished","1921-10-01","2005-11-25");
INSERT INTO `venues` VALUES ("2736","Florida Citrus Bowl","Orlando, Florida","active","1936-01-01","NULL");
INSERT INTO `venues` VALUES ("2737","Foxboro Stadium","Foxborough, Massachusetts","demolished","1971-08-15","2002-01-19");
INSERT INTO `venues` VALUES ("2779","Volksparkstadion","Hamburg","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2780","Rheinstadion","Düsseldorf","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2781","Parkstadion","Gelsenkirchen","demolished","1973-08-04","2008-11-17");
INSERT INTO `venues` VALUES ("2782","Stadio delle Alpi","Torino","active","NULL","NULL");
INSERT INTO `venues` VALUES ("2947","Estadi de Sarrià","Barcelona","demolished","1923-02-18","1997-09-20");
INSERT INTO `venues` VALUES ("14115","Estadio Carlos Tartiere","Oviedo","active","NULL","NULL");
